# must be run on root
FROM node:18-alpine

RUN apk update && apk add --no-cache nginx

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

WORKDIR /app

COPY package*.json ./
RUN yarn install

COPY . .

RUN rm -rf pages/editor \
  && find pages/api -type f \
     -not -path "pages/api/images/\[id\].ts" \
     -exec rm -f {} \;

EXPOSE 80

CMD ["./deploy/entrypoint.front.sh"]

