# must be run on root
FROM node:18-alpine

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

WORKDIR /app

COPY package*.json ./
RUN yarn install

COPY . .

RUN rm -f pages/editors.tsx \
  && find pages/api -type f \
     -not -path "pages/api/images/\[id\].ts" \
     -exec rm -f {} \;

EXPOSE 3000

CMD ["./deploy/entrypoint.editor.sh"]

