name: Trigger Netlify Build

on:
  schedule:
    - cron: '15 5,17 * * *'

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.netlifyBuildUrl }}
